version: "3.9"

services:
  app:
    build:
      # build docker file under the current directory
      # and where the command is going to run from
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      # map app directory in the project to the app directory of the container
      # this way the local changes are going to be reflected in the container in
      # real time
      - ./app:/app
      - dev-static-data:/vol/web
    # default command to run the service
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      #sets initial db configuration
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  # volume-name: <if empty -> default file system location for the name volumes>
  dev-db-data:
  dev-static-data:
