---
# needs to be called .yml and be inside this path
# this file is going to be performing checks
# --- signals it's a yml file

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # the Linux version below has docker-composer already installed
    runs-on: ubuntu-20.04
    # if any of these steps fail, then the whole job fails
    steps:
      - name: Login to Docker hub
        # uses: allows to use a pre-made actions that's
        # provided in the Github actions repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # checks out the code in GitHub actions job to
        # make sure the code is there
        uses: actions/checkout@v2
      - name: Test
        # run UnitTests probvided in the Django project
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"